#######################################################################	

all: 	broadcast.exec 

#######################################################################	

## Broadcast
broadcast.exec: broadcast.cpp
	mpicxx -O3 broadcast.cpp -o broadcast.exec

## Reduce



## Scatter



## Calculating pi




#######################################################################	
	
clean :
	rm -f *.exec
